### ISSUE TITLE
 Error: The requested accessory 'VizioDisplay' was not registered by any plugin

### ISSUE THREAD

**Issue by bgedney** [JohnWickham/homebridge-vizio#4]
I installed the package with `npm install homebridge-vizio`.  Ran the setup, added the accessory to the config. 

```systemd[1]: Started Node.js HomeKit Server.
homebridge[2750]: ┌──────────────────────────────────────────────────────────────┐
homebridge[2750]: │                   npm update check failed                    │
homebridge[2750]: │             Try running with sudo or get access              │
homebridge[2750]: │             to the local update config store via             │
homebridge[2750]: │ sudo chown -R $USER:$(id -gn $USER) /home/homebridge/.config │
homebridge[2750]: └──────────────────────────────────────────────────────────────┘
homebridge[2750]: [2018-9-14 09:40:14] Loaded config.json with 1 accessories and 2 platforms.
homebridge[2750]: [2018-9-14 09:40:14] ---
homebridge[2750]: [2018-9-14 09:40:14] Loaded plugin: homebridge-camera-ffmpeg-ufv
homebridge[2750]: [2018-9-14 09:40:14] Registering platform 'homebridge-camera-ffmpeg-ufv.camera-ffmpeg-ufv'
homebridge[2750]: [2018-9-14 09:40:14] ---
homebridge[2750]: [2018-9-14 09:40:15] Loaded plugin: homebridge-nest
homebridge[2750]: [2018-9-14 09:40:15] Registering platform 'homebridge-nest.Nest'
homebridge[2750]: [2018-9-14 09:40:15] ---
homebridge[2750]: [2018-9-14 09:40:15] Loading 2 platforms...
homebridge[2750]: [2018-9-14 09:40:15] [Nest] Initializing Nest platform...
homebridge[2750]: [2018-9-14 09:40:15] [Nest] Fetching Nest devices.
homebridge[2750]: [2018-9-14 09:40:15] [UniFi Video (ffmpeg)] Initializing camera-ffmpeg-ufv platform...
homebridge[2750]: [2018-9-14 09:40:15] Loading 1 accessories...
homebridge[2750]: /usr/lib/node_modules/homebridge/lib/api.js:64
homebridge[2750]: throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
homebridge[2750]: ^
homebridge[2750]: Error: The requested accessory 'VizioDisplay' was not registered by any plugin.
homebridge[2750]: at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
homebridge[2750]: at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:285:42)
homebridge[2750]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
homebridge[2750]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
homebridge[2750]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge[2750]: at Module._compile (internal/modules/cjs/loader.js:654:30)
homebridge[2750]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
homebridge[2750]: at Module.load (internal/modules/cjs/loader.js:566:32)
homebridge[2750]: at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
homebridge[2750]: at Function.Module._load (internal/modules/cjs/loader.js:498:3)
homebridge[2750]: at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
homebridge[2750]: at startup (internal/bootstrap/node.js:201:19)
homebridge[2750]: at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
```

Accessory section reads:

```    "accessories": [
        {
            "accessory": "VizioDisplay",
            "name": "DownstairsDisplay",
            "token": "--Redacted--",
            "address": "xxx.xxx.xxx.xxx"
        }
    ]
```

When I pull the config, it runs fine.  

The module is owned by root, but all the supporting files and parent directory have an O+R perm....

```
# ls -lah ./node_modules/homebridge-vizio
total 28K
drwxr-xr-x  2 root root 4.0K Sep 14 09:34 .
drwxr-xr-x 64 root root 4.0K Sep 14 09:34 ..
-rw-r--r--  1 root root 2.1K Apr 11 07:05 index.js
-rw-r--r--  1 root root  914 Apr  7 18:37 .npmignore
-rw-r--r--  1 root root 1.3K Sep 14 09:10 package.json
-rw-r--r--  1 root root 1.9K Apr  7 18:49 README.md
-rw-r--r--  1 root root 1.5K Apr  7 18:24 setup.js
```

Am I missing something or is this a bug?

**Comment by JohnWickham** [comment]
Homebridge usually gives that error when the plugin wasn't installed properly — try `npm install -g homebridge-vizio` to install it globally instead.
